name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: Node kur
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Paketleri kur
        run: npm install

      - name: Testleri çalıştır
        run: npm test
